### ISSUE TITLE
Can only view emails in 'INBOX'

### ISSUE THREAD

**Issue by thetomester13** [jasonmunro/hm3#2]
Even when I have multiple accounts added, I can only view the emails under their direct inbox. 'Email => All', 'Main => Everything', and 'Main => Unread' all tell me I'm 'so alone'....

**Comment by jasonmunro** [comment]
Combined views use a system to aggregate data sources that we should be able to track down pretty easily to determine what is broken here.

1. On a combined view page (any of the above are fine), look at the HTML source and search for the js function name hm_data_sources. It should be returning a list of all your accounts.

2. In the upper right hand corner of the display for combined views are 3 icons. The middle one should display a div with the sources for this view. Do your sources show up here?

3. When you load a combined view, one AJAX request per data source should fire on page load. Do you see these AJAX requests in the console?

Let me know and I'm sure we can track this down and get if fixed in no time!

**Comment by jasonmunro** [comment]
I re-tested in Firefox to see if this was browser related but still could not reproduce. Combined views are time limited per data source (you can see this in the message list heading area). You can configure that for a view by clicking the cog icon in the upper right which will take you to that view's settings section.

So it's possible this is working, but there are no messages within the default time range (the default is 1 day, and if your timezone is not setup, it might result in no matches). Try bumping that range out to 2 weeks for a combined view and see if it makes a difference. Also be sure to setup your timezone in the "general" area of the settings page.

**Comment by thetomester13** [comment]
Yep, you're totally right. I didn't realize that it was based on a time range. Once adjusted, messages show up just as they should!
